unstable_features = true
use_field_init_shorthand = true
newline_style = "Unix"
group_imports="StdExternalCrate"
imports_granularity= "Crate"
format_code_in_doc_comments=true
wrap_comments=true
comment_width=100
format_strings=true
normalize_comments=true
empty_item_single_line=false
format_macro_matchers=true
reorder_impl_items=true
